version: '3'
services: 
    webserverapache:
        env_file: 
            - ./project.env
        build: ./webserver
        ports: 
            - "8080:80"
            - "1433:443"
        volumes: 
            #Modificar la part a la esquerra de : y possar on estroben els fitxers de configuració, o els fitxers de dades del apache
            - ./Apache_config:/etc/apache2/sites-available
            - ./Apache_files:/var/www 